server:
  port: 8001
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启网关通过ID访问
      routes:
        - id: main-service
          uri: lb://main-service
          predicates:
            - Path=/main/**
      default-filters:
        - StripPrefix=1
        - RemoveRequestHeader=Origin
        #- name: Hystrix
        #  args:
           # name: fallbackcmd
           # fallbackUri: forward:/defaultHystrixFallback
      httpclient:
        pool:
          max-idle-time: 10000
          max-connections: 10000
          acquire-timeout: 15000



#hystrix.command.fallbackcmd.execution.isolation.thread.timeoutInMilliseconds: 3000000




eureka:
  client:
    service-url:
      defaultZone: http://eureka-register:8000/eureka/
    registry-fetch-interval-seconds: 3
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 3
    lease-expiration-duration-in-seconds: 3
logging:
  config: classpath:log.xml

jwt:
  #不需要验证的接口（配置规则： /服务名/具体接口）
  skipUrls: /api-test/test,
    /login,
    /download,
    /upload/img/,
    /open/,
    /lj/