server:
  port: 8002
spring:
  application:
    name: main-service

  datasource:
    name: te
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
     driver-class-name: com.mysql.cj.jdbc.Driver
     url: jdbc:mysql://localhost:3306/tibet_account?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
     username: root
     password: 2020jdream

  resources:
    static-locations: classpath:/upload/img/,file:D:/new_workspace_java/Tibet_server/


  data:
    mongodb:
      host: localhost
      database: tibet
      #username: 'ant'
      #password: '123456'
      port: 27017
  devtools:
    livereload:
      enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka
    registry-fetch-interval-seconds: 3
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 3
    lease-expiration-duration-in-seconds: 3
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
  config: classpath:log.xml